# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
ratio_cpp <- function(x, y) {
    .Call('_OPER782Package_ratio_cpp', PACKAGE = 'OPER782Package', x, y)
}

rcpp_hello_world <- function() {
    .Call('_OPER782Package_rcpp_hello_world', PACKAGE = 'OPER782Package')
}

